apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: macadmins-munki-web
  name: munki-repo-pvc 
  namespace: wksmgmt
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
